In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine, text

In [2]:
solar_df = pd.read_csv(
    "solar_plant_cleaned_data.csv",
    parse_dates=['date_time']
)

In [3]:
solar_df['date'] = solar_df['date_time'].dt.date
solar_df['month'] = solar_df['date_time'].dt.to_period('M').astype(str)

In [4]:
db_user = os.getenv("MYSQL_USER")
db_password = os.getenv("MYSQL_PASSWORD")

In [5]:
engine = create_engine(
    f"mysql+pymysql://{db_user}:{db_password}@localhost:3306/SOLARDB"
)

In [6]:
solar_df.to_sql(
    name="fact_solar_generation",
    con=engine,
    if_exists="replace",
    index=False
)

36823

In [7]:
from sqlalchemy import text

pd.read_sql(
    text("SHOW TABLES;"),
    engine
)

       Tables_in_solardb
0  fact_solar_generation
1             solar_data
2              solar_int
3               solar_pr

In [8]:
pd.read_sql(
    text("DESCRIBE fact_solar_generation;"),
    engine
)

                     Field      Type Null Key Default Extra
0                date_time  datetime  YES        None
1                 plant_id    bigint  YES        None
2              inverter_id      text  YES        None
3                 dc_power    double  YES        None
4                 ac_power    double  YES        None
5              daily_yield    double  YES        None
6              total_yield    double  YES        None
7                     hour    bigint  YES        None
8        weather_sensor_id      text  YES        None
9      ambient_temperature    double  YES        None
10      module_temperature    double  YES        None
11  solar_irradiation_kwm2    double  YES        None
12          efficiency_pct    double  YES        None
13           power_loss_kw    double  YES        None
14               temp_diff    double  YES        None
15          specific_yield    double  YES        None
16                    date      date  YES        None
17                   month      text  YES        None

In [9]:
pd.read_sql(text("""
SELECT
    inverter_id,
    ROUND(AVG(efficiency_pct), 2) AS avg_efficiency_pct
FROM fact_solar_generation
GROUP BY inverter_id
ORDER BY avg_efficiency_pct ASC
"""), engine)

        inverter_id  avg_efficiency_pct
0   1BY6WEcLGh8j5v7                9.77
1   1IF53ai7Xc0U56Y                9.77
2   3PZuoBAID5Wc2HD                9.77
3   7JYdWkrLSPkdwr4                9.77
4   McdE0feGgRqW7Ca                9.77
5   WRmjgnKYAwPKWDb                9.77
6   ZnxXDlPa8U1GXgE                9.77
7   ZoEaEvLYb1n2sOq                9.77
8   adLQvlD726eNBSB                9.77
9   bvBOhCH3iADSZry                9.77
10  iCRJl6heRkivqQ3                9.77
11  ih0vzX44oOqAx2f                9.77
12  pkci93gMrogZuBj                9.77
13  rGa61gmuvPhdLxV                9.77
14  sjndEbLyjtCKgGv                9.77
15  uHbuxQJl8lW7ozc                9.77
16  wCURE6d3bPkepu2                9.77
17  z9Y9gH1T5YWrNuG                9.77
18  zBIq5rxdHJRwDNY                9.77
19  zVJPv84UY57bAof                9.77
20  VHMLBKoKgIrUVDU                9.77
21  YxYtjZvoooNbGkE                9.77

In [10]:
pd.read_sql(text("""
SELECT
    ROUND(
        AVG((dc_power - ac_power) / dc_power * 100),
        2
    ) AS avg_energy_loss_pct
FROM fact_solar_generation
WHERE dc_power > 0
"""), engine)

   avg_energy_loss_pct
0                90.23

In [11]:
pd.read_sql(text("""
SELECT
    month,
    ROUND(AVG(ac_power), 2) AS avg_ac_power
FROM fact_solar_generation
GROUP BY month
ORDER BY month
"""), engine)

     month  avg_ac_power
0  2020-05        593.51
1  2020-06        556.93

In [12]:
pd.read_sql(text("""
SELECT
    date,
    ROUND(MAX(daily_yield), 2) AS daily_energy_kwh
FROM fact_solar_generation
GROUP BY date
ORDER BY date
"""), engine)

          date  daily_energy_kwh
0   2020-05-15           6469.71
1   2020-05-16           6712.12
2   2020-05-17           7865.50
3   2020-05-18           5506.00
4   2020-05-19           7002.29
5   2020-05-20           9101.62
6   2020-05-21           7991.50
7   2020-05-22           7376.62
8   2020-05-23           8782.88
9   2020-05-24           8395.43
10  2020-05-25           9162.86
11  2020-05-26           8222.00
12  2020-05-27           6857.00
13  2020-05-28           8635.38
14  2020-05-29           8343.00
15  2020-05-30           7418.50
16  2020-05-31           6300.00
17  2020-06-01           6126.75
18  2020-06-02           7606.38
19  2020-06-03           8009.43
20  2020-06-04           8391.71
21  2020-06-05           7919.62
22  2020-06-06           6601.71
23  2020-06-07           8352.75
24  2020-06-08           8619.00
25  2020-06-09           8308.43
26  2020-06-10           6665.62
27  2020-06-11           5789.62
28  2020-06-12           5987.43
29  2020-06-13           8773.71
30  2020-06-14           7589.38
31  2020-06-15           6916.00
32  2020-06-16           6395.62
33  2020-06-17           6109.14

In [13]:
pd.read_sql(text("""
SELECT
    inverter_id,
    ROUND(AVG(specific_yield), 4) AS avg_specific_yield
FROM fact_solar_generation
GROUP BY inverter_id
ORDER BY avg_specific_yield ASC
"""), engine)

        inverter_id  avg_specific_yield
0   bvBOhCH3iADSZry          12666.6203
1   1BY6WEcLGh8j5v7          12838.4103
2   ih0vzX44oOqAx2f          13499.9699
3   ZoEaEvLYb1n2sOq          13590.3366
4   zBIq5rxdHJRwDNY          13661.7906
5   7JYdWkrLSPkdwr4          13666.9812
6   YxYtjZvoooNbGkE          13689.6276
7   rGa61gmuvPhdLxV          13701.7025
8   z9Y9gH1T5YWrNuG          13706.3853
9   sjndEbLyjtCKgGv          13724.7150
10  WRmjgnKYAwPKWDb          13744.0068
11  pkci93gMrogZuBj          13746.4382
12  zVJPv84UY57bAof          13771.2281
13  wCURE6d3bPkepu2          13788.7674
14  iCRJl6heRkivqQ3          13815.4004
15  uHbuxQJl8lW7ozc          13881.7562
16  ZnxXDlPa8U1GXgE          13895.9807
17  VHMLBKoKgIrUVDU          13979.6203
18  McdE0feGgRqW7Ca          13985.1198
19  3PZuoBAID5Wc2HD          13993.7468
20  1IF53ai7Xc0U56Y          14033.5723
21  adLQvlD726eNBSB          14253.9168

In [14]:
pd.read_sql(text("""
SELECT
    plant_id,
    ROUND(AVG(efficiency_pct), 2) AS avg_efficiency_pct,
    ROUND(
        AVG((dc_power - ac_power) / dc_power * 100),
        2
    ) AS avg_energy_loss_pct,
    ROUND(MAX(daily_yield), 2) AS peak_daily_yield
FROM fact_solar_generation
WHERE dc_power > 0
GROUP BY plant_id
"""), engine)

   plant_id  avg_efficiency_pct  avg_energy_loss_pct  peak_daily_yield
0   4135001                9.77                90.23           9162.86